### PR TITLE
M36

### PR DESCRIPTION
**Pull request by decodedfiles**
👋🏻

### CODE REVIEW

**Review by decodedfiles — COMMENTED** [review]
😀

**Comment by decodedfiles** [comment]
> 👋🏻

**Comment by decodedfiles** [comment]
> 👋🏻

**Comment by stormi266** [comment]
I do not know why I am subscribed to this but maybe you can help me because somebody has taken over my computer and phone and it looks like my phone is a computer now and they’re in my Microsoft account and they’re using get hub to do a lot of the stuff

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sorinj** [comment]
You are getting these emails because somehow you or a bot signed you up for a GitHub account here https://github.com/decodedfiles, forked this repository, and you are no getting notifications. You could go to the account settings in Github and make changes there, as needed.

**Pull request closed without merging**
