### PR TITLE
Update Software Construction Toolkit instructions Wiki link

### PR DESCRIPTION
**Pull request by pr1s10n3r**

### CODE REVIEW

**Review by larry18001 — COMMENTED** [review]
- https://github.com/google/omaha.
-(url)https://github.com/google/omaha.git
- `gh repo clone google/omaha`

**Comment by larry18001** [comment]
`gh repo clone google/omaha`
[https://github.com/google/omaha.git](url)

**Comment by ZDYUSS4** [comment]
#response_container_BBPPID{font-family: "Century Gothic", CenturyGothic, Geneva, AppleGothic, sans-serif; font-size:8pt; color: initial;}                                                                                                                                               ***@***.***                                                                                                                                                                           From: ***@***.***: 21 November 2022 10:44 amTo: ***@***.*** to: ***@***.***: ***@***.***: Re: [google/omaha] Update Software Construction Toolkit instructions Wiki link (PR #487)  
gh repo clone google/omaha
https://github.com/google/omaha.git

**Review by Bbbbnnzismwismwkdbsmwowmdjdn — APPROVED** [review]

**Review by Yfz777 — APPROVED** [review]

**Comment by Jaxsonkai** [comment]
> _ No description provided. _
https://www.google.com/search?q=google+calendar+-+event+details+%282%29.pdf&tbm=isch

**Pull request closed without merging**
