### PR TITLE
Minor edits to the Markdown to improve readability and correct a few …

### PR DESCRIPTION
**Pull request by gabegundy**
* Minor edits to the Markdown to improve readability and corrected a few typos.

* Note about atlserver location.

* Made docs link relative in the README.md

I was going to hold-off on a PR until I had more edits gathered up, but the readability was so much greater on the DeveloperSetupGuide.md that I thought... "early and often" :)

Let me know if you need anything at all before you can accept it. Thanks!

### CODE REVIEW

**Comment by gabegundy** [comment]
I signed it!

**Comment by gabegundy** [comment]
Let's try this again! :)

**Comment by sorinj** [comment]
Thank you for fixing and improving the content. I suggest not linking dependencies to personal github repositories. Would that be ok with you?
Thank you!

**Comment by Montesdodgers13** [comment]
Update Googlechrome

**Comment by gabegundy** [comment]
@sorinj I would love to, but I don't know what else to do. I don't think it's likely Google would put them in their namespace. What would you recommend? I do think they needed to be pulled in somewhere and CodePlex is going down and the others are bit rotting on various sites.

BTW, I'm still working on making this easier to build :)

**Comment by jpawlicki** [comment]
Thanks again for your contribution! Sorry for the push-back, but...

As far as we know, the Google Code Archive is not scheduled for shutdown and so the existing link can stay (at least until people begin committing to the swtoolkit project again, at which point it will be the responsibility of the maintainers of that project to transition it to github).

We have a similar position on ATLServer: until Microsoft transitions the project to github, we are comfortable linking to the archival version on CodePlex.

**Comment by gabegundy** [comment]
Go ahead and delete this pull request. Thanks.

**Pull request closed without merging**
