### PR TITLE
update version as 1.3.31.5

### PR DESCRIPTION
**Pull request by MelissaDietz**

### CODE REVIEW

**Comment by sorinj** [comment]
What is the problem we are trying to solve with this pull request? The version on master must be 1.3.99.0. It is intentionally chosen to be higher than other branch version, so the build from the master can over-install any build from the branch.

**Comment by stanleyroycrosss** [comment]
Pull

**Comment by sorinj** [comment]
We are going to close this pull request as spam.

**Comment by lamlylom90** [comment]
Ok and pull

**Comment by b0923280516** [comment]
2016年10月14日 下午5:43，"lamlylom90" <notifications@github.com>寫道：

**Comment by Chimdashu** [comment]
更新版本1.3.31.5#95

**Comment by Chimdashu** [comment]
更新版本為1.3.31.5#95

**Pull request closed without merging**
